---
- name: copy etcd.sh from local
  ansible.builtin.copy:
    src: ./roles/node1/files/etcd.sh
    dest: /home/vagrant/etcd_dir
    mode: 0755

- name: copy 99-calico.conflist from local
  ansible.builtin.copy:
    src: ./roles/node1/files/99-calico.conflist
    dest: /etc/cni/net.d/
  become: yes

- name: copy calicoctl.cfg from local
  ansible.builtin.copy:
    src: ./roles/node1/files/calicoctl.cfg
    dest: /etc/calico/
  become: yes
