---
- name: git clone cni-plugin
  ansible.builtin.git:
    repo: https://github.com/containernetworking/plugins.git
    dest: /home/vagrant/plugins

- name: build cni-plugin
  ansible.builtin.shell: 
    cmd: ./build_linux.sh
    chdir: /home/vagrant/plugins/
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

- name: Ensure /opt/cni directory exists
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0755
  become: yes

- name: Ensure /etc/cni/net.d directory exists
  file:
    path: /etc/cni/net.d
    state: directory
    mode: 0755
  become: yes

- name: Ensure /etc/calico directory exists
  file:
    path: /etc/calcio
    state: directory
    mode: 0755
  become: yes

- name: Copy plugins/bin directory to /opt/cni
  ansible.builtin.copy:
    src: /home/vagrant/plugins/bin/
    dest: /opt/cni/bin/
    remote_src: yes
    mode: 0755
  become: yes

- name: install calicoctl binary
  ansible.builtin.get_url:
    dest: /usr/local/bin/calicoctl
    url: https://github.com/projectcalico/calico/releases/download/v3.28.0/calicoctl-linux-amd64
    mode: 0755
  become: yes
